### ISSUE TITLE
Cancel NotificationCenter when app inactive?

### ISSUE THREAD

**Issue by harryhieunguyen** [Aikyuichi/notification_center.dart#1]
When app is inactive status, do I need to cancel NotificationCenter and subscribe it back when app resume?
Does it work like StreamSubscription?
Thanks

**Comment by Aikyuichi** [comment]
Yes, otherwise the NotificationCenter will continue firing notifications.
For next release, I can implement pause and resume methods similar to those of the StreamSubscription

**Comment by harryhieunguyen** [comment]
Great, thank you, your work helps a lot, looking for next release

Currently I just let it firing, no cancel even when app is inactive, when app resumes, it still works well. Not sure if it's good practice
