### ISSUE TITLE
Concurrent modification during iteration: Instance(length:0) of '_GrowableList'.

### ISSUE THREAD

**Issue by sovannarithsok** [Aikyuichi/notification_center.dart#2]
Latest release version 1.0.0

It happened when unsubscribe notification:

         Concurrent modification during iteration: Instance(length:0) of '_GrowableList'.
        I/flutter (26152): #0      ListIterator.moveNext (dart:_internal/iterable.dart:348:7)
        I/flutter (26152): #1      NotificationCenter.unsubscribe (package:notification_center/notification_center.dart:43:30)
        I/flutter (26152): <asynchronous suspension>

**Comment by Aikyuichi** [comment]
Hi
Fixed on 1.0.1
